#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

source ~/app-root/data/.bash_profile
# Activate VirtualEnv in order to use the correct libraries
source ~/python/virtenv/bin/activate
export PYTHON_EGG_CACHE=$OPENSHIFT_PYTHON_DIR/virtenv/lib/python2.7

echo 'Syncing database...'
python $OPENSHIFT_REPO_DIR/wsgi/training/manage.py syncdb
python $OPENSHIFT_REPO_DIR/wsgi/training/manage.py migrate
echo 'Done'
